import fs from "fs/promises";
import path from "path";

/**
 * Saves the final report to disk as both .json and .md
 * Output folder: project_root/outputs/
 */
export async function saveReportToDisk(
  topic: string,
  report: any,
  runMeta: {
    duration_ms: number;
    summaries_count: number;
    claims_count: number;
    overall_confidence: number;
  }
): Promise<{ jsonPath: string; mdPath: string }> {
  // outputs/ sits at project root (one level above src/)
  const outputDir = path.resolve(process.cwd(), "outputs");
  await fs.mkdir(outputDir, { recursive: true });

  // Slugify topic for filename
  const slug = topic
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .substring(0, 60);
  const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
  const base = `${slug}__${timestamp}`;

  // ── 1. JSON ──────────────────────────────────────────────────────────────
  const jsonPath = path.join(outputDir, `${base}.json`);
  await fs.writeFile(
    jsonPath,
    JSON.stringify({ meta: runMeta, report }, null, 2),
    "utf-8"
  );

  // ── 2. Markdown ───────────────────────────────────────────────────────────
  const mdPath = path.join(outputDir, `${base}.md`);
  const md = buildMarkdown(topic, report, runMeta);
  await fs.writeFile(mdPath, md, "utf-8");

  console.log(`💾 Report saved:`);
  console.log(`   JSON → ${jsonPath}`);
  console.log(`   MD   → ${mdPath}`);

  return { jsonPath, mdPath };
}

function buildMarkdown(topic: string, report: any, meta: any): string {
  const confidence = (meta.overall_confidence * 100).toFixed(0);
  const duration = (meta.duration_ms / 1000).toFixed(1);

  const lines: string[] = [
    `# ${report.topic ?? topic}`,
    ``,
    `> **Overall Confidence:** ${confidence}% &nbsp;|&nbsp; **Duration:** ${duration}s &nbsp;|&nbsp; **Claims analysed:** ${meta.claims_count}`,
    ``,
    `---`,
    ``,
    `## Introduction`,
    ``,
    report.introduction ?? "",
    ``,
  ];

  // Sections
  for (const section of report.sections ?? []) {
    lines.push(`## ${section.heading}`);
    lines.push(``);
    lines.push(section.content ?? "");
    lines.push(``);
    if (section.notes) {
      lines.push(`> ⚠️ ${section.notes}`);
      lines.push(``);
    }
    if (section.sources?.length) {
      lines.push(`**Sources:** ${section.sources.join(", ")}`);
      lines.push(``);
    }
  }

  // Consensus / disagreements (Phase 3 reports)
  if (report.metadata?.consensus) {
    lines.push(`## Consensus`);
    lines.push(``);
    lines.push(report.metadata.consensus);
    lines.push(``);
  }
  if (report.metadata?.disagreements) {
    lines.push(`## Areas of Disagreement`);
    lines.push(``);
    lines.push(report.metadata.disagreements);
    lines.push(``);
  }

  // Conclusion
  lines.push(`## Conclusion`);
  lines.push(``);
  lines.push(report.conclusion ?? "");
  lines.push(``);

  // Sources
  const sources: string[] =
    report.sources_cited ?? report.metadata?.sources ?? [];
  if (sources.length) {
    lines.push(`---`);
    lines.push(``);
    lines.push(`## Sources`);
    lines.push(``);
    for (const s of sources) lines.push(`- ${s}`);
    lines.push(``);
  }

  // Run metadata footer
  lines.push(`---`);
  lines.push(``);
  lines.push(
    `*Generated by Multi-Agent Research Pipeline on ${new Date().toUTCString()}*`
  );

  return lines.join("\n");
}